### ISSUE TITLE
USB Lines Criss-Cross Fix is not Working

### ISSUE THREAD

**Issue by patrickpoirier51** [gumstix/PKG900000001531#3]
The Coral chip is not detected on my Gumstix Raspberry Pi CM4 + Pixhawk FMUv6.

After having exhausted all the software and configuration issues, I decided to test on the CM4 IO board with my own Coral USB stick and all worked OK.

This is when I decided to investigate this hardware rework on the USB lines
![image](https://user-images.githubusercontent.com/12484190/113036259-0dd7c880-9162-11eb-9e09-cec30e99c43d.png)

Being a criss-cross it appear that the runs had to be cut.... and its not the case.
So I cut them:
![image](https://user-images.githubusercontent.com/12484190/113036351-2ba52d80-9162-11eb-9600-55268fafd6be.png)

Now I can see the USB device:
dmesg | grep usb
New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.04
lsusb
Bus 001 Device 002: ID 1a6e:089a Global Unichip Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

But when I launch the test , the python test start but it never finalise the test  with sporadic bus speed errors messages on terminal.

Conclusion: This quick fix does not work properly as it expose and unbalance the USB data lines.

**Comment by smithandrewc** [comment]
Yes, you received some early production test units that were known to have communication issues with the Coral chip.  We have made some changes and are building a new version now.

**Comment by patrickpoirier51** [comment]
Ah, OK.....  
Well, let me know when these will be ready to ship

**Comment by patrickpoirier51** [comment]
Hello,  When are You planning to release the new boards so we can finish the ArduPilot integration ?

**Comment by smithandrewc** [comment]
We're building a new version now. However, it is only making changes to the CM4 and Coral. How does this affect Ardupilot?

**Comment by patrickpoirier51** [comment]
I am taking part of the CM4 integration, so I need a fully functionnal unit in order to build a complete image.

**Comment by smithandrewc** [comment]
Well unfortunately due to scarcity of parts, I don't expect us to have a decent volume of these for a couple of months.  I would recommend you get a hold of an external USB coral device and CM4 board and do whatever testing you can.

Alternatively, you can get one of our Uprev AI and CM Robo boards
https://www.gumstix.com/cm4-uprev-ai.html
https://www.gumstix.com/cm-robo.html
Put the CM4 on the Uprev AI and into the Robo board and either connect the UART header on the Robo to GPS header on the Pixhawk or use the USB ports on the two boards.  It'll require some minor changes to get the MAVLink data on those channels but would get you as close as possible to the finished board.  If you're interested in pursuing either avenue, get a hold of our customer support.

**Comment by mariorra** [comment]
Hi Guys! Thanks for sharing this issue

I arrive here bc I'm working on a solution that provides something similar. But let see that it is something there that makes me confuse. 
The Version that I have is the 4. There the schematic shows the following connection. I wrote by hand the red lines to define what was the issue in the past. 

![GITHUB_issue](https://user-images.githubusercontent.com/6213523/129759418-4d63ca17-b31f-46aa-bc0f-0bb1cc297e6d.png)

My confusion is if I follow the connection between the ASM1142 and CORAL:

ASM1142                     LABEL                             LABEL             CORAL
USB1_SSTX_P PIN42    USB1_SSTX_P   -->    USB1_SSTX_N   PCIE_RX_P
USB1_SSTX_N PIN43   USB1_SSTX_N  -->     USB1_SSTX_P    PCIE_RX_N

Are the polarity well defined in the TX lines?
Is the issue fixed on the side of the labels? 
Do I have to follow the labels in order to have a good connection using the guidelines that google provides? 

Thanks in advance

**Comment by smithandrewc** [comment]
The initial post in this thread was in regards to the error in swapping the polarity of the USB2 signals.  That has been fixed.  Your question about swapping the polarity of the SSTX lines is intentional.  The superspeed signals allow for polarity inversion to allow for better routing (i.e. not using vias).  We made use of that.

**Comment by mariorra** [comment]
Ok, great. Thanks for the answer. Do you have any other comments that avoid to waste the time and money according to your experience with both modules?
